# Generated by Django 4.2.24 on 2026-01-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookReviewApp', '0002_alter_books_id_alter_reviews_id_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='DefaultUser', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
