# Generated by Django 4.2.24 on 2026-01-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookReviewApp', '0003_users_name_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
