# Generated by Django 4.2.24 on 2026-01-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookReviewApp', '0004_alter_books_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
    ]
