# Generated by Django 4.2.24 on 2026-01-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookReviewApp', '0005_alter_books_isbn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
