# Generated by Django 4.2.24 on 2026-01-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookReviewApp', '0006_rename_books_book_rename_reviews_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
